#Begin code for PA2 of CS260
loctree : loctree.py
	python3 loctree.py

lcrstree : lcrstree.py
	python3 lcrstree.py

mergelists : arraylist.py listconcat.py mergelists.py
	python3 mergelists.py

listconcat : arraylist.py listconcat.py
	python3 listconcat.py

huffman : huffman.py loctree.py
	python3 huffman.py

time : timing.py loctree.py lcrstree.py
	python3 timing.py

levelorder : levelorder.py loctree.py
	python3 levelorder.py

pointerqueue : pointerqueue.py
	python3 pointerqueue.py

clean : 
	@if [ -d __pycache__ ] ; then\
		rm -r __pycache__;\
	fi;
