#Begin code for PA3 of CS260
openhash : openhash.py
	python3 openhash.py

closedhash : closedhash.py
	python3 closedhash.py

bst : bst.py
	python3 bst.py

trie : trie.py
	python3 trie.py

dijkstra : dijkstra.py
	python3 dijkstra.py

floyd : floyd.py
	python3 floyd.py

dfs : dfs.py
	python3 dfs.py

clean :
	@if [ -d __pycache__ ] ; then\
		rm -r __pycache__;\
	fi;
